version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-health-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: ai-health-ui
    ports:
      - "5173:80"
    depends_on:
      - backend